// New unit guide and extension labs; share the original app's settings and learning record.
const learningRoute=[
 {id:'prepare',title:['先備準備','Prerequisites'],time:['10 分鐘','10 min'],goal:['會求直線截距、解二元一次聯立方程式、比較不等式。','Find intercepts, solve two simultaneous linear equations, and compare inequalities.'],task:['先完成下方 3 題先備檢查。若不熟悉，先複習代入法與消去法，再到平行直線實驗。','Complete the three prerequisite checks below. Review substitution and elimination if needed, then explore parallel lines.'],section:'lab',mode:'parallel'},
 {id:'lines',title:['看懂平行直線與半平面','Parallel lines and half-planes'],time:['20 分鐘','20 min'],goal:['能說明係數、截距、平移與斜率的關係，能辨識實線和虛線邊界。','Explain coefficients, intercepts, translation and slope; distinguish solid and dashed boundaries.'],task:['閱讀主題 01–02（教材 p.9–14）。固定 a,b 改變 k，再用測試點驗證 ≤、≥、<、> 的解在哪一側。','Read lessons 01–02 (pp.9–14). Fix a,b and vary k; use test points to check ≤, ≥, <, >.'],section:'lab',mode:'half'},
 {id:'feasible',title:['從交集找到可行頂點','Find feasible vertices'],time:['20 分鐘','20 min'],goal:['能逐一檢查所有限制，求兩條邊界交點，排除不可行交點。','Check every constraint, find boundary intersections, and reject infeasible intersections.'],task:['閱讀主題 03（p.14–17），在例題 4 點選各頂點；把 (0,0)、(3,0)、(2,2)、(0,3) 代入 x + 3y。','Read lesson 03 (pp.14–17). Click the Example 4 vertices and evaluate x + 3y at (0,0), (3,0), (2,2), (0,3).'],section:'lab',model:0},
 {id:'model',title:['把生活情境寫成模型','Turn a situation into a model'],time:['25 分鐘','25 min'],goal:['能定義變數與單位，區分「不超過」與「至少」，選擇最大化或最小化。','Define variables and units, distinguish “at most” from “at least”, and choose maximize or minimize.'],task:['閱讀主題 04–05（p.18–20）。先遮住解答，自行列精油與合金限制式，再用互動圖形驗證。','Read lessons 04–05 (pp.18–20). Write oil and alloy constraints before reading the solutions, then verify them in the graph lab.'],section:'learn'},
 {id:'practice',title:['練習、回饋與修正','Practice, feedback and revision'],time:['20 分鐘','20 min'],goal:['能解釋答案，並辨認錯誤發生在建模、計算或解讀哪一步。','Explain answers and identify whether an error came from modeling, calculation or interpretation.'],task:['完成至少 5 次練習，查看每題解析；再完成 10 題測驗。未達 80 分時，回到錯誤題型的主題與圖形實驗。','Complete at least five practice attempts and read each explanation, then take the ten-question quiz. Below 80%, revisit the relevant lessons and graphs.'],section:'practice'},
 {id:'extend',title:['進階探究與學習整理','Extension and reflection'],time:['25 分鐘','25 min'],goal:['能分辨整數與連續解，判斷無解、無界及多重最佳解，說明資源改變的影響。','Distinguish integer and continuous solutions, identify infeasibility, unboundedness and multiple optima, and explain resource changes.'],task:['完成五個進階探究。寫下「我改了什麼、圖形如何改變、為什麼答案改變」，最後下載學習紀錄。','Explore the five extension labs. Explain what you changed, how the graph changed and why the answer changed, then download your records.'],section:'advanced'}
];
const prerequisites=[
 q('先備檢查',0,'2x + y = 6 的 y 截距？','What is the y-intercept of 2x + y = 6?', ['2','3','6','−6'],2,'令 x = 0，得到 y = 6。','Set x = 0 to obtain y = 6.'),
 q('先備檢查',0,'x + y = 4、x − y = 2 的交點？','Find the intersection of x + y = 4 and x − y = 2.', ['(2,2)','(3,1)','(1,3)','(4,0)'],1,'兩式相加得 2x = 6，x = 3，再代入得 y = 1。','Add the equations: 2x = 6, so x = 3 and y = 1.'),
 q('先備檢查',0,'(1,2) 是否滿足 x + 2y ≤ 6？','Does (1,2) satisfy x + 2y ≤ 6?', ['是 / Yes','否 / No'],0,'1 + 2×2 = 5 ≤ 6，所以成立。','1 + 2×2 = 5 ≤ 6, so it does.')
];
const diagnostic={};let advancedMode='sensitivity',extensionState={budget:80,capacity:7,integer:true,b:2,status:'bounded',shipx:40,shipy:10};
function openRoute(step){if(step.mode){mode=step.mode;labState={}}if(step.model!==undefined){mode='opt';modelIndex=step.model;labState={}}navigate(step.section)}
function renderGuide(){const completed=learningRoute.filter(s=>visited.includes('guide-'+s.id)).length,attempts=history.filter(h=>h.type==='practice').length,results=history.filter(h=>h.type==='quiz_result'),top=results.length?Math.max(...results.map(h=>h.detail.score)):null;
root.innerHTML=`<div class="guidehero card"><span class="tag">${t('學習指引・可分 3 次上課或依自己的速度完成','Learning guide · Three sessions or your own pace')}</span><h2>${t('學習這個單元，從哪裡開始？','Where should you begin?')}</h2><p>${t('本單元的核心不是背答案，而是能用「限制條件 + 目標函數」說明如何找到最佳選擇。建議依下列路線操作，每段先預測，再驗證，最後用自己的話解釋。','The goal is to explain the best choice using constraints and an objective. Follow the route below: predict first, verify next, then explain it in your own words.')}</p><div class="guideobjectives"><span>① ${t('看懂限制','Read constraints')}</span><span>② ${t('找出可行區域','Find feasibility')}</span><span>③ ${t('比較最佳解','Compare optima')}</span><span>④ ${t('解釋實際意義','Interpret results')}</span></div><progress value="${completed}" max="6"></progress><p>${t('學習路線自我檢核','Route self-check')}: ${completed}/6 · ${t('練習','Practice')}: ${attempts} · ${t('測驗最高分','Best quiz')}: ${top??'—'}</p><p class="muted">${t('完成按鈕代表你的自我確認，測驗成績是另一項理解證據。總建議時間約 120 分鐘，可分段完成。','Completion buttons record your self-check; quiz scores provide separate evidence. Suggested total: about 120 minutes, divided as needed.')}</p></div>
<h2>${t('六步學習路線','Six-step learning route')}</h2><div class="cards guidecards">${learningRoute.map((s,i)=>`<article class="card"><div class="row"><span class="stepnumber">${i+1}</span><span class="tag orange">${tx(s.time)}</span></div><h3>${tx(s.title)}</h3><p><strong>${t('學習目標：','Goal: ')}</strong>${tx(s.goal)}</p><p>${tx(s.task)}</p><div class="row"><button data-route="${s.id}" class="primary">${t('前往操作','Open activity')}</button><button data-route-done="${s.id}">${visited.includes('guide-'+s.id)?t('✓ 已完成','✓ Completed'):t('我已完成','Mark complete')}</button></div></article>`).join('')}</div>
<h2>${t('先備檢查：先試再看解析','Prerequisite checks: try before reading')}</h2><div class="cards">${prerequisites.map((q,i)=>`<article class="card" id="diagnostic-${i}">${questionMarkup(q,'diagnostic-'+i,diagnostic[i])}<button data-diagnostic="${i}">${t('檢查與複習','Check and review')}</button><div id="diagnosticFeedback-${i}" aria-live="polite">${diagnostic[i]!==undefined?feedback(q,diagnostic[i]):''}</div></article>`).join('')}</div>
<div class="grid" style="margin-top:22px"><article class="card"><h3>${t('常見錯誤提醒','Common mistakes')}</h3><ul><li>${t('先確認變數單位：公斤、公噸、百公斤不能混用。','Keep units consistent: kg, tonnes and hundreds of kg are different.')}</li><li>${t('測試點不要選在邊界上；乘以負數時不等號需反向。','Use a test point off the boundary; multiplying by a negative reverses an inequality.')}</li><li>${t('兩條線的交點不一定可行：必須符合全部限制。','A line intersection must satisfy every constraint to be feasible.')}</li><li>${t('非負條件應由情境決定，不能隨意加在所有教材問題。','Add nonnegativity when the context requires it; do not impose it on every problem.')}</li><li>${t('整數問題不能直接四捨五入連續最佳解。','Do not simply round a continuous optimum in an integer problem.')}</li></ul></article><article class="card"><h3>${t('完成後，我能做到嗎？','Can you do this independently?')}</h3><p>${t('不看解析，說出可行解、目標函數與最佳解的差別。從一個情境列式，求出頂點並解釋最佳解的單位。','Without the solutions, explain feasible points, objectives and optima. Model a situation, find vertices and interpret the units.')}</p><p>${t('測驗 ≥ 80 分：進入延伸；60–79 分：針對錯題再練習；低於 60 分：重新完成平行直線、半平面與頂點法。','Quiz ≥ 80: proceed to extensions. 60–79: practice weak areas. Below 60: revisit parallel lines, half-planes and vertices.')}</p><div class="row"><button data-guide-link="quiz">${t('理解測驗','Understanding quiz')}</button><button data-guide-link="history">${t('查看與下載紀錄','View and download records')}</button></div></article></div>`;
root.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>openRoute(learningRoute.find(s=>s.id===b.dataset.route)));
root.querySelectorAll('[data-route-done]').forEach(b=>b.onclick=()=>{let id='guide-'+b.dataset.routeDone;if(!visited.includes(id)){visited.push(id);log('guide_complete',{step:b.dataset.routeDone});sound()}renderGuide()});
root.querySelectorAll('[data-diagnostic]').forEach(b=>b.onclick=()=>{let i=+b.dataset.diagnostic,r=$(`input[name=diagnostic-${i}]:checked`);if(!r){toast(t('請先選擇答案。','Choose an answer first.'));return}diagnostic[i]=+r.value;$('#diagnosticFeedback-'+i).innerHTML=feedback(prerequisites[i],diagnostic[i]);log('prerequisite',{question:tx(prerequisites[i].text),correct:diagnostic[i]===prerequisites[i].answer});sound(diagnostic[i]===prerequisites[i].answer)});root.querySelectorAll('[data-guide-link]').forEach(b=>b.onclick=()=>navigate(b.dataset.guideLink));
}
const extensionTopics=[['sensitivity','資源敏感度','Resource sensitivity','🌱'],['integer','整數規劃','Integer optimization','🔢'],['multiple','多重最佳解','Multiple optima','◇'],['status','無解、無界與嚴格邊界','Infeasibility and bounds','∞'],['transport','運輸規劃','Transportation','🚚']];
const extensionChallenges={
 sensitivity:q('進階探究',0,'精油模型的預算常數 B 從 80 改為 87，其他條件不變，最大產量增加多少公斤？','In the oil model, increase budget RHS B from 80 to 87. How much does maximum yield increase?', ['7','11','25','84'],1,'此區間最佳點為 ((120−B)/7,(3B−150)/7)，P = (1200+11B)/7。因此增加 7 單位預算常數，產量增加 11 公斤。','Here the optimum is ((120−B)/7,(3B−150)/7), with P = (1200+11B)/7. A 7-unit RHS increase adds 11 kg.'),
 integer:q('進階探究',0,'非負整數 x,y 滿足 2x + 3y ≤ 7，3x + 4y 的最大值？','For nonnegative integers x,y with 2x + 3y ≤ 7, maximize 3x + 4y.', ['9','10','10.5','12'],1,'連續解 (3.5,0) 的值為 10.5；整數最優解為 (2,1)，值為 10。四捨五入成 (4,0) 會違反限制。','The continuous optimum (3.5,0) gives 10.5. The integer optimum (2,1) gives 10. Rounding to (4,0) violates the constraint.'),
 multiple:q('進階探究',0,'在例題 4 的區域最大化 x + 2y，哪種敘述正確？','Maximize x + 2y over Example 4’s region. Which statement is correct?', ['只有 (0,3) / Only (0,3)','只有 (2,2) / Only (2,2)','(0,3) 到 (2,2) 整段都是 / The whole segment (0,3)–(2,2)','沒有最佳解 / No optimum'],2,'在邊界 x + 2y = 6 上的這段線，每點都可行且 P = 6。','Every point on this feasible edge satisfies P = 6.'),
 status:q('進階探究',0,'x,y ≥ 0、x + y < 4 時，最大化 x + y，答案應如何表達？','With x,y ≥ 0 and x + y < 4, how should the maximum of x + y be described?', ['最大值 4 / Maximum 4','最大值 0 / Maximum 0','沒有最大值，上確界 4 / No maximum; supremum 4','無可行解 / Infeasible'],2,'可以越來越接近 4，但所有可行點都小於 4，邊界不包含，故取不到最大值。','Feasible values approach 4 but never reach it because the boundary is excluded.'),
 transport:q('進階探究',0,'甲庫運 A 40 噸、B 10 噸，乙庫運 B 40 噸，總運費？','Depot 1 ships 40 tonnes to A and 10 to B; depot 2 ships 40 to B. Total cost?', ['50000','54000','61000','65000'],1,'40×500 + 10×600 + 40×700 = 54000 元；甲庫用完 50 噸，乙庫使用 40 噸、剩 20 噸。','40×500 + 10×600 + 40×700 = 54000. Depot 1 uses 50 tonnes; depot 2 uses 40 and has 20 left.')
};
const challengeAnswers={};
function renderAdvanced(){root.innerHTML=`<div class="card extensionintro"><span class="tag purple">${t('教材延伸・從會算到會判斷','Textbook extensions · Beyond calculation')}</span><h2>${t('進階與延伸學習','Advanced and extended learning')}</h2><p>${t('先完成主題學習與例題 4–6，再選一個探究。每次先預測結果、操作圖形驗證，再完成挑戰題。這些內容是教材的延伸設計，並非原教材新增頁面。','Complete the lessons and Examples 4–6 first. Choose a lab, predict, explore and answer its challenge. These are new extensions, not additional textbook pages.')}</p></div><div class="extensionnav" role="group" aria-label="${t('選擇進階探究','Choose extension lab')}">${extensionTopics.map(([id,z,e,icon])=>`<button class="${id===advancedMode?'primary':''}" data-extension="${id}" aria-pressed="${id===advancedMode}">${icon} ${t(z,e)}</button>`).join('')}</div><div class="grid"><article class="card"><div id="extensionGraph"></div><p id="extensionGraphNote" class="muted"></p></article><article class="card" id="extensionControls"></article></div><div id="extensionLesson" class="card" style="margin-top:22px"></div><div id="extensionChallenge" class="card" style="margin-top:22px"></div>`;root.querySelectorAll('[data-extension]').forEach(b=>b.onclick=()=>{advancedMode=b.dataset.extension;renderAdvanced();log('extension_visit',{topic:advancedMode})});({sensitivity:renderSensitivity,integer:renderInteger,multiple:renderMultiple,status:renderStatuses,transport:renderTransport})[advancedMode]();drawExtensionChallenge();const inspect=e=>{const point=e.target.closest('[data-point]');if(!point)return;if(e.type==='keydown'&&!['Enter',' '].includes(e.key))return;if(e.type==='keydown')e.preventDefault();toast(point.getAttribute('aria-label'));log('extension_point',{topic:advancedMode,point:point.getAttribute('aria-label')})};$('#extensionGraph').onclick=inspect;$('#extensionGraph').onkeydown=inspect}
function updateExtensionSlider(id,key,update){$('#'+id).oninput=()=>{extensionState[key]=+$('#'+id).value;$('#'+id+'Value').textContent=fmt(extensionState[key]);update()};$('#'+id).onchange=()=>log('extension_change',{topic:advancedMode,parameter:key,value:extensionState[key]})}
function bestOf(cons,a,b,max=true){const vs=vertices(cons),values=vs.map(([x,y])=>a*x+b*y),value=max?Math.max(...values):Math.min(...values);return {vs,values,value,winners:vs.filter((p,i)=>Math.abs(values[i]-value)<1e-7)}}
function renderSensitivity(){const get=B=>bestOf([[5,4,B],[3,1,30]],25,12);$('#extensionControls').innerHTML=`<span class="tag">${t('例題 5・精油模型延伸','Example 5 · Oil model extension')}</span><h3>${t('增加預算，就一定同樣有效嗎？','Does every budget increase help equally?')}</h3><div class="math">max P = 25x + 12y<br>5x + 4y ≤ B<br>3x + y ≤ 30; x,y ≥ 0</div>${slider('budget',t('預算限制常數 B','Budget RHS B'),extensionState.budget,20,150,1)}<p class="muted">${t('原預算限制為 15x + 12y ≤ 240（萬元），除以 3 得 B = 80；實際預算為 3B 萬元。','Original budget: 15x + 12y ≤ 240 (10,000 units). Divide by 3 to get B = 80; actual budget = 3B × 10,000.')}</p><div id="sensitivityResult" class="result" aria-live="polite"></div><button id="budgetReset">${t('還原 B = 80','Reset B = 80')}</button>`;
function update(){let B=extensionState.budget,r=get(B),next=get(B+1),gain=next.value-r.value;$('#extensionGraph').innerHTML=graph({min:-1,max:33,cons:[[5,4,B],[3,1,30],[-1,0,0],[0,-1,0]],line:[25,12,r.value],points:r.vs});$('#extensionGraphNote').textContent=t('綠色是可行區域；橘色是最佳等值線。x,y 的單位是公噸。','Green: feasible region; orange: optimal level line. x,y are tonnes.');$('#sensitivityResult').innerHTML=`<strong>${t('最大產量','Maximum yield')}: ${fmt(r.value)} ${t('公斤','kg')}</strong><br>${t('最佳原料用量','Optimal amounts')}: ${r.winners.map(p=>`(${fmt(p[0])},${fmt(p[1])})`).join(' / ')}<br>${t('B 再增加 1 的產量增益','Gain if B increases by 1')}: ${fmt(gain)} ${t('公斤','kg')}`}
updateExtensionSlider('budget','budget',update);$('#budgetReset').onclick=()=>{extensionState.budget=80;$('#budget').value=80;$('#budgetValue').textContent='80';update()};update();$('#extensionLesson').innerHTML=`<h3>${t('觀察、解釋、延伸','Observe, explain, extend')}</h3><p>${t('依序試 B = 40、80、120、140。B < 50 時，全部使用 A 原料最佳；50 < B < 120 時，成本與廢棄物兩條限制都緊束；B > 120 後，廢棄物限制主導，增加預算不再提高產量。','Try B = 40, 80, 120, 140. Below 50, using only A is optimal. Between 50 and 120, both constraints bind. Above 120, waste is the bottleneck and extra budget does not increase yield.')}</p><div class="scroll"><table><thead><tr><th>B</th><th>${t('最大產量（公斤）','Maximum yield (kg)')}</th><th>${t('區間内每增加 1 的增益','Marginal gain inside interval')}</th></tr></thead><tbody>${[40,80,120,140].map(B=>`<tr><td>${B}</td><td>${fmt(get(B).value)}</td><td>${B<50?'5':B<120?'11/7 ≈ 1.571':'0'}</td></tr>`).join('')}</tbody></table></div><p>${t('這是資源敏感度的概念：邊際收益只在同一最優結構的區間內維持。此處 B 的 1 單位相當於實際預算增加 3 萬元，不能混淆單位。','This is resource sensitivity: marginal gains remain constant only within the same optimal structure. One unit of B means 30,000 in actual budget; keep units clear.')}</p>`}
function renderInteger(){$('#extensionControls').innerHTML=`<span class="tag orange">${t('整數點與連續區域','Integer points and a continuous region')}</span><h3>${t('生產件數，真的能用小數嗎？','Can a product count be fractional?')}</h3><div class="math">max P = 3x + 4y<br>2x + 3y ≤ C; x,y ≥ 0</div>${slider('capacity',t('資源上限 C','Resource limit C'),extensionState.capacity,5,15,1)}<label>${t('變數類型','Variable type')}<select id="integerType"><option value="integer" ${extensionState.integer?'selected':''}>${t('非負整數','Nonnegative integers')}</option><option value="continuous" ${!extensionState.integer?'selected':''}>${t('非負連續實數','Nonnegative real values')}</option></select></label><div id="integerResult" class="result" aria-live="polite"></div><div id="integerTable" class="scroll"></div>`;function update(){let C=extensionState.capacity,cons=[[2,3,C]],continuous=bestOf(cons,3,4),points=[];for(let x=0;x<=Math.floor(C/2);x++)for(let y=0;y<=Math.floor(C/3);y++)if(2*x+3*y<=C)points.push([x,y]);let best=Math.max(...points.map(([x,y])=>3*x+4*y)),winner=points.filter(([x,y])=>3*x+4*y===best),value=extensionState.integer?best:continuous.value;$('#extensionGraph').innerHTML=graph({min:-.5,max:8.5,cons:[...cons,[-1,0,0],[0,-1,0]],line:[3,4,value],points:extensionState.integer?points:continuous.vs}).replace(/<text[^>]*>\([^<]*<\/text>/g,'');$('#extensionGraphNote').textContent=t('整數模式的每個綠點都是可行整數點；連續模式則允許區域內的小數座標。','In integer mode, every green point is a feasible integer point. Continuous mode permits fractional coordinates.');$('#integerResult').innerHTML=`<strong>${t('整數最大值','Integer maximum')}: ${fmt(best)}</strong> ${t('於','at')} ${winner.map(p=>`(${p})`).join(' / ')}<br>${t('連續最大值','Continuous maximum')}: ${fmt(continuous.value)} ${t('於','at')} ${continuous.winners.map(p=>`(${fmt(p[0])},${fmt(p[1])})`).join(' / ')}<br>${t('可行整數點數量','Number of feasible integer points')}: ${points.length}`;$('#integerTable').innerHTML=`<table><thead><tr><th>${t('整數最佳點','Optimal integer point')}</th><th>P</th></tr></thead><tbody>${winner.map(p=>`<tr><td>(${p})</td><td>${best}</td></tr>`).join('')}</tbody></table>`}
updateExtensionSlider('capacity','capacity',update);$('#integerType').onchange=()=>{extensionState.integer=$('#integerType').value==='integer';update();log('extension_change',{topic:'integer',integer:extensionState.integer})};update();$('#extensionLesson').innerHTML=`<h3>${t('為什麼不能直接四捨五入？','Why rounding does not solve integer optimization')}</h3><p>${t('C = 7 時，連續最佳解是 (3.5,0)，P = 10.5。四捨五入成 (4,0) 需要 8 單位資源，超過 7；往下取整成 (3,0) 雖可行，P = 9，仍不如整數點 (2,1) 的 P = 10。','At C = 7, the continuous optimum is (3.5,0), P = 10.5. Rounding to (4,0) uses 8 units, exceeding 7. Rounding down to (3,0) is feasible but gives 9, below (2,1), which gives 10.')}</p><p>${t('請試 C = 6、7、8：比較整數與連續最大值的差距。原教材 p.22 習題 5 是「數整數點」，此處進一步在整數點中找最佳解。','Try C = 6, 7, 8 and compare integer and continuous values. Textbook p.22 Exercise 5 counts integer points; this lab additionally optimizes over them.')}</p>`}
function renderMultiple(){$('#extensionControls').innerHTML=`<span class="tag purple">${t('目標係數的敏感度','Objective coefficient sensitivity')}</span><h3>${t('最佳解為什麼會突然換位置？','Why can the optimum switch vertices?')}</h3><div class="math">max P = x + by<br>x + 2y ≤ 6; 2x + y ≤ 6<br>x,y ≥ 0</div>${slider('objectiveB',t('目標 y 係數 b','Objective y coefficient b'),extensionState.b,0,3,.1)}<div id="multipleResult" class="result" aria-live="polite"></div><button id="parallelEdge">${t('設成 b = 2，觀察整條最優邊','Set b = 2: view an optimal edge')}</button>`;function update(){let b=extensionState.b,r=bestOf([[1,2,6],[2,1,6]],1,b);$('#extensionGraph').innerHTML=graph({min:-.2,max:4,cons:[[1,2,6],[2,1,6],[-1,0,0],[0,-1,0]],line:[1,b,r.value],points:r.vs});$('#extensionGraphNote').textContent=t('當橘線與可行區域的一條邊重合，該線段上每點都是最佳解。','When the orange line coincides with a feasible edge, every point on that segment is optimal.');$('#multipleResult').innerHTML=`<strong>${t('最大值','Maximum')}: ${fmt(r.value)}</strong><br>${t('最優頂點','Optimal vertices')}: ${r.winners.map(p=>`(${p})`).join(' / ')}<br>${r.winners.length>1?t('有無限多個最佳解：上述頂點之間的整段線。','Infinitely many optima: the full segment between these vertices.'):t('唯一最佳解；微調係數，觀察是否換到另一個頂點。','Unique optimum. Adjust the coefficient and watch for a vertex switch.')}`}
updateExtensionSlider('objectiveB','b',update);$('#parallelEdge').onclick=()=>{extensionState.b=2;$('#objectiveB').value=2;$('#objectiveBValue').textContent=2;update()};update();$('#extensionLesson').innerHTML=`<h3>${t('分段比較，理解最優位置','Compare intervals to understand optimal locations')}</h3><p>${t('四個頂點的目標值為 0、3、2 + 2b、3b。0 ≤ b < 0.5 時 (3,0) 最佳；b = 0.5 時 (3,0) 到 (2,2) 整段最佳；0.5 < b < 2 時 (2,2) 最佳；b = 2 時 (2,2) 到 (0,3) 整段最佳；b > 2 時 (0,3) 最佳。','The four vertex values are 0, 3, 2 + 2b, 3b. For 0 ≤ b < 0.5, (3,0) is optimal. At 0.5, the edge to (2,2) is optimal. For 0.5 < b < 2, (2,2) is optimal. At 2, the edge to (0,3) is optimal. Above 2, (0,3) is optimal.')}</p><p>${t('原教材 p.23 習題 9 也用兩點同時取最大值求 k；原理是目標等值線與最優邊平行。','Textbook p.23 Exercise 9 also uses two simultaneous optimal points to find k: the objective line is parallel to an optimal edge.')}</p>`}
const statuses={
 bounded:{cons:[[1,1,4]],line:[1,1,4],desc:['x,y ≥ 0；x + y ≤ 4','x,y ≥ 0; x + y ≤ 4'],result:['最大值 4，可以在整段 x + y = 4 的可行邊取到。最小值 0。','Maximum 4, attained on the full feasible edge x + y = 4. Minimum 0.'],why:['非空、封閉、有界，所以最大值與最小值都存在。','Nonempty, closed and bounded: both extrema exist.']},
 unbounded:{cons:[[-1,-1,-4]],line:[1,1,8],desc:['x,y ≥ 0；x + y ≥ 4','x,y ≥ 0; x + y ≥ 4'],result:['最大化 x + y：沒有有限最大值。最小化 x + y：有最小值 4。','Maximizing x + y: no finite maximum. Minimizing x + y: minimum 4.'],why:['沿 (t,0)，t ≥ 4 可無限增加目標；但最小值仍在邊界。無界區域不代表所有目標都無最佳解。','Along (t,0) for t ≥ 4, the objective grows without bound. The minimum is still on the boundary. Unbounded regions do not rule out every finite optimum.']},
 infeasible:{cons:[[1,1,2],[-1,-1,-4]],line:null,desc:['x,y ≥ 0；x + y ≤ 2 且 x + y ≥ 4','x,y ≥ 0; x + y ≤ 2 and x + y ≥ 4'],result:['無可行解，因此也沒有最佳解。','No feasible point, so no optimum.'],why:['同一個 x + y 不可能同時 ≤ 2 又 ≥ 4。先檢查可行性，不能把兩條邊界的值當作答案。','The same x + y cannot be both ≤ 2 and ≥ 4. Check feasibility before optimizing.']},
 strict:{cons:[[1,1,4]],line:[1,1,4],desc:['x,y ≥ 0；x + y < 4（邊界不包含）','x,y ≥ 0; x + y < 4 (boundary excluded)'],result:['沒有最大值；上確界是 4。最小值 0 可取到。','No maximum; supremum 4. Minimum 0 is attained.'],why:['(4−ε,0)，0 < ε < 4 的目標值能任意接近 4，但不能等於 4。畫出的虛線不屬於可行區域。','Points (4−ε,0), 0 < ε < 4, approach 4 but never reach it. The dashed boundary is excluded.']}
};
function renderStatuses(){$('#extensionControls').innerHTML=`<span class="tag orange">${t('先問有沒有解，再問最佳解','Check feasibility before optimizing')}</span><h3>${t('四種情況比較','Compare four cases')}</h3><label>${t('限制條件情境','Constraint scenario')}<select id="statusSelect">${[['bounded','封閉有界','Closed and bounded'],['unbounded','無界但可行','Unbounded and feasible'],['infeasible','限制衝突：無解','Conflicting: infeasible'],['strict','嚴格不等式','Strict inequality']].map(([id,z,e])=>`<option value="${id}" ${extensionState.status===id?'selected':''}>${t(z,e)}</option>`).join('')}</select></label><div id="statusMath" class="math"></div><div id="statusResult" class="result" aria-live="polite"></div><p id="statusWhy"></p>`;function update(){let s=statuses[extensionState.status],svg=graph({min:-.4,max:8,cons:[...s.cons,[-1,0,0],[0,-1,0]],line:extensionState.status==='strict'?null:s.line});if(extensionState.status==='strict')svg=svg.replace('class="boundary"','class="boundary" stroke-dasharray="8 6"');$('#extensionGraph').innerHTML=svg;$('#extensionGraphNote').textContent=t('圖框只是顯示範圍，不是限制式。無界區域仍向圖外延伸；無解情況沒有綠色交集。','The graph frame is a viewport, not a constraint. An unbounded region extends beyond it; infeasibility has no green intersection.');$('#statusMath').textContent=tx(s.desc);$('#statusResult').textContent=tx(s.result);$('#statusWhy').textContent=tx(s.why);$('#statusResult').className='result'+(extensionState.status==='infeasible'?' bad':'')}
$('#statusSelect').onchange=()=>{extensionState.status=$('#statusSelect').value;update();log('extension_change',{topic:'status',scenario:extensionState.status})};update();$('#extensionLesson').innerHTML=`<h3>${t('避免把「無界」和「無解」混在一起','Distinguish unboundedness from infeasibility')}</h3><p>${t('無解是「沒有任何點符合全部限制」；無界是「可行區域往某方向無限延伸」。區域無界時，必須再看目標函數能否沿可行方向無限改善。嚴格不等式則可能只有上確界或下確界，取不到極值。','Infeasible means no point satisfies all constraints. Unbounded means the region extends indefinitely. Then check whether the objective can improve without bound along feasible directions. Strict inequalities may yield only a supremum or infimum.')}</p><p>${t('連結教材：例題 6 的區域無界，成本仍有最小值；例題 3 使用嚴格不等式時，要注意虛線邊界。','Textbook connection: Example 6 has an unbounded region but a finite cost minimum. Example 3 illustrates strict, dashed boundaries.')}</p>`}
function renderTransport(){$('#extensionControls').innerHTML=`<span class="tag">${t('教材 p.22 習題 8・運輸配置','Textbook p.22 Exercise 8 · Transportation')}</span><h3>${t('把貨物送對地方，運費怎麼省？','Allocate shipments to minimize cost')}</h3><p>${t('甲、乙庫存 50、60 噸；A、B 工廠需要 40、50 噸。x,y 是甲庫送往 A、B 的噸數。','Depots 1,2 hold 50,60 tonnes. A,B require 40,50. Let x,y be depot 1 shipments to A,B.')}</p>${slider('shipx',t('甲 → A：x（噸）','Depot 1 → A: x (tonnes)'),extensionState.shipx,0,40)}${slider('shipy',t('甲 → B：y（噸）','Depot 1 → B: y (tonnes)'),extensionState.shipy,0,50)}<div id="transportResult" class="result" aria-live="polite"></div><button id="transportBest" class="primary">${t('顯示最低運費配置','Show minimum-cost allocation')}</button><div class="scroll" id="transportTable"></div>`;function update(){let x=extensionState.shipx,y=extensionState.shipy,valid=x+y>=30&&x+y<=50,cost=61000-150*x-100*y;$('#extensionGraph').innerHTML=graph({min:-3,max:55,cons:[[1,0,40],[0,1,50],[1,1,50],[-1,-1,-30],[-1,0,0],[0,-1,0]],line:[150,100,61000-cost],sample:[x,y]});$('#extensionGraphNote').textContent=t('粉紅點是目前配送方案；綠色區域是符合庫存及需求的方案。','Pink point: current allocation. Green region: allocations satisfying stocks and demands.');$('#transportResult').className='result'+(valid?'':' bad');$('#transportResult').innerHTML=`<strong>${valid?t('✓ 可行配送','✓ Feasible allocation'):t('✗ 配送不可行','✗ Infeasible allocation')}</strong><br>${t('甲庫使用','Depot 1 usage')}: ${x+y}/50 ${t('噸','tonnes')} · ${t('乙庫使用','Depot 2 usage')}: ${90-x-y}/60 ${t('噸','tonnes')}<br>${valid?t('總運費：','Total cost: ')+cost+t(' 元',''):t('甲庫最多供應 50 噸；若甲庫少於 30 噸，乙庫將超過 60 噸。此配置不能當作可行成本。','Depot 1 can supply at most 50 tonnes; below 30, depot 2 would exceed 60. This allocation has no feasible cost.')}`;$('#transportTable').innerHTML=`<table><thead><tr><th>${t('路線','Route')}</th><th>${t('噸數','Tonnes')}</th><th>${t('單價','Rate')}</th></tr></thead><tbody><tr><td>${t('甲 → A','1 → A')}</td><td>${x}</td><td>500</td></tr><tr><td>${t('甲 → B','1 → B')}</td><td>${y}</td><td>600</td></tr><tr><td>${t('乙 → A','2 → A')}</td><td>${40-x}</td><td>650</td></tr><tr><td>${t('乙 → B','2 → B')}</td><td>${50-y}</td><td>700</td></tr></tbody></table>`}
updateExtensionSlider('shipx','shipx',update);updateExtensionSlider('shipy','shipy',update);$('#transportBest').onclick=()=>{extensionState.shipx=40;extensionState.shipy=10;for(let id of ['shipx','shipy']){$('#'+id).value=extensionState[id];$('#'+id+'Value').textContent=extensionState[id]}update();sound();log('extension_optimum',{topic:'transport',x:40,y:10,cost:54000})};update();$('#extensionLesson').innerHTML=`<h3>${t('從四條運輸路線，化成兩個變數','Reduce four shipment routes to two variables')}</h3><div class="math">0 ≤ x ≤ 40; 0 ≤ y ≤ 50<br>30 ≤ x + y ≤ 50<br>min P = 500x + 600y + 650(40−x) + 700(50−y)<br>= 61000 − 150x − 100y</div><p>${t('甲庫的兩條路線都比較便宜，但甲庫只有 50 噸。每噸改由甲送 A 能省 150 元，送 B 能省 100 元，所以先滿足 A 的 40 噸，再把甲剩下的 10 噸送 B；乙送 B 40 噸，最低運費 54000 元。','Depot 1 is cheaper on both routes but has only 50 tonnes. Using depot 1 saves 150 per tonne to A and 100 to B. Supply all 40 tonnes to A first, then 10 to B. Depot 2 supplies B’s remaining 40; minimum cost = 54000.')}</p><p>${t('延伸思考：如果甲到 B 的運費從 600 降成 500，優先配送的順序會改變嗎？甲到 B 每噸可省 200 元，應先用甲的 50 噸滿足 B。此題先以分析回答，以上互動仍使用原教材單價。','Extension: if depot 1 → B drops from 600 to 500, does the priority change? Its saving becomes 200 per tonne, so allocate depot 1’s 50 tonnes to B first. Analyze this separately; the controls above retain textbook rates.')}</p>`}
function drawExtensionChallenge(){let item=extensionChallenges[advancedMode],selected=challengeAnswers[advancedMode];$('#extensionChallenge').innerHTML=`<span class="tag purple">${t('探究後挑戰','Post-exploration challenge')}</span>${questionMarkup(item,'extensionAnswer',selected)}<button class="primary" id="checkExtension">${t('檢查答案並記錄','Check and record')}</button><div id="extensionFeedback" aria-live="polite">${selected!==undefined?feedback(item,selected):''}</div>`;$('#checkExtension').onclick=()=>{let r=$('input[name=extensionAnswer]:checked');if(!r){toast(t('請先選擇答案。','Choose an answer first.'));return}let answer=+r.value;challengeAnswers[advancedMode]=answer;log('extension_challenge',{topic:advancedMode,question:tx(item.text),correct:answer===item.answer,selected:item.choices[answer],answer:item.choices[item.answer]});sound(answer===item.answer);$('#extensionFeedback').innerHTML=feedback(item,answer)}}
// Include new concept checks in the shared repeat-practice and quiz pool.
questions.push(...Object.values(extensionChallenges),
 q('進階延伸',0,'精油模型 B > 120 時，再增加預算能否提高最大產量？','For the oil model with B > 120, does extra budget increase maximum yield?', ['能 / Yes','不能 / No'],1,'廢棄物限制 3x + y ≤ 30 已成瓶頸。最佳點 (0,30)，P = 360，不再受預算限制。','Waste is the bottleneck. The optimum (0,30) yields 360 and no longer depends on the budget.'),
 q('進階延伸',0,'x + y ≤ 2 與 x + y ≥ 4 同時成立的可行區域？','What is the feasible region for x + y ≤ 2 and x + y ≥ 4?', ['三角形 / Triangle','無界區域 / Unbounded region','空集合 / Empty set','直線 / Line'],2,'同一個量無法同時 ≤ 2 且 ≥ 4，所以交集為空。','A quantity cannot be both ≤ 2 and ≥ 4, so the intersection is empty.'),
 q('進階延伸',0,'運輸模型的甲庫量 x + y 為何至少是 30 噸？','Why must depot 1 ship at least 30 tonnes in the transport model?', ['甲有 30 噸 / Stock is 30','總需求 90，乙最多 60 / Demand 90; depot 2 capacity 60','A 需要 30 噸 / A requires 30','單價是 30 / Rate is 30'],1,'總需求 40 + 50 = 90，乙庫最多 60，所以甲庫至少要供應 30。','Total demand is 90. Depot 2 supplies at most 60, so depot 1 must supply at least 30.')
);
